services:
  - type: web
    name: resume-analyzer-backend
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
